name: Cow Says Fortune
description: Generate a random fortune using a cow ASCII art.
runs:
  using: composite
  steps:
    - name: Install fortune cowsay
      run: |
        sudo apt-get update
        sudo apt-get install -y fortune cowsay
      shell: bash

    - name: Generate fortune
      run: |
        fortune | cowsay
      shell: bash
